// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delete.sql

package database

import (
	"context"
)

const dELETEALLUSERS = `-- name: DELETEALLUSERS :exec
DELETE  from users
`

func (q *Queries) DELETEALLUSERS(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, dELETEALLUSERS)
	return err
}
